import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Language = "English" | "हिन्दी" | "Español" | "Français" | "Deutsch" | "中文";

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    // Nav & General
    home: "Home",
    services: "Services",
    reports: "Reports",
    contact: "Contact",
    signOut: "Sign out",
    logoTitle: "AI Early",
    logoSubtitle: "Detector",
    High: "High",
    Moderate: "Moderate",
    Low: "Low",
    
    // Hero
    heroTitle: "AI Early",
    heroGradient: "Detector",
    heroSub: "Empowering you with client-side Deep Learning models to screen for critical health conditions before they progress. Smart Care. Early Detection.",
    getStarted: "Start Screening",
    vitalsCalc: "Track Vitals",
    
    // Services Section
    whatWeDo: "What We Do",
    ourServices: "Our Services",
    servicesTitle: "Trusted health intelligence,",
    servicesSubtitle: "at a glance",
    servicesDesc: "Choose a module to get started with AI-driven early detection.",
    openModule: "Open module →",

    // Feature Cards
    triageHubTitle: "Symptom Triage Hub",
    triageHubDesc: "Select a specialized machine learning screening module to begin your risk assessment.",
    cancerTitle: "Cancer Checker",
    cancerDesc: "AI-powered early detection and screening for various types of cancer with high accuracy.",
    arthritisTitle: "Arthritis Checker",
    arthritisDesc: "Intelligent analysis and early detection of arthritis symptoms using advanced AI models.",
    heartTitle: "Heart Attack Checker",
    heartDesc: "Cardiovascular risk screening using AI on lifestyle, vitals and family-history factors.",
    covidTitle: "COVID-19 Checker",
    covidDesc: "Symptom-based COVID-19 risk assessment with real-time AI scoring and confidence.",
    tbTitle: "Tuberculosis Checker",
    tbDesc: "Early TB risk detection using respiratory and exposure-related signals.",
    aidsTitle: "AIDS / HIV Checker",
    aidsDesc: "Confidential HIV/AIDS risk screening based on validated clinical risk factors.",
    reportsTitle: "Report Checker",
    reportsDesc: "Automated medical report analysis and interpretation powered by machine learning.",
    vitalsTitle: "Vitals Tracker",
    vitalsDesc: "Calculate and monitor health indicators (BMI, Training Zones, MAP) on device.",
    adminTitle: "Admin",
    adminDesc: "Manage users, view analytics, and configure system settings from a centralized dashboard.",
    assistantTitle: "Personal Assistant",
    assistantDesc: "Track daily steps, water intake, sleep cycles, calories, and manage medication reminders.",
    mentalTitle: "Mental Wellness Hub",
    mentalDesc: "Analyze stress levels, practice guided breathing, listen to ambient sounds, and log mood.",
    doctorTitle: "Doctor & SOS Center",
    doctorDesc: "Instant emergency SOS triggers, search nearby clinics, ambulance contacts, and CPR guides.",
    diabetesTitle: "Diabetes & Diet Planner",
    diabetesDesc: "Monitor blood sugar levels, plan healthy custom meals, and check workout recommendations.",
    educationTitle: "Educational Hub",
    educationDesc: "Bust common health myths, play interactive medical quizzes, and read wellness news.",
    
    // Adhira Chatbot
    botName: "Adhira",
    botRole: "AI Health Triage Assistant",
    botWelcome: "Hii! My name is Adhira, your AI health assistant. Describe what symptoms you are experiencing (e.g. chest pain, joint stiffness, cough) and I will guide you to the right screening module.",
    botPlaceholder: "Type symptoms (e.g. chest tightness, fever)...",
    botSend: "Send",
    botTriageHeart: "Your symptoms suggest potential cardiovascular concern. Please take our Heart Attack risk screener immediately.",
    botTriageArthritis: "You mentioned joint symptoms, which suggest potential arthritic concern. We recommend taking our Arthritis screener.",
    botTriageCovid: "Based on your symptoms, there could be a risk of COVID-19. We advise checking with our COVID-19 screener.",
    botTriageTb: "Your respiratory symptoms indicate a potential risk of Tuberculosis. Please run the TB risk screener.",
    botTriageCancer: "You noted warning flags that could relate to oncological conditions. Please complete the Cancer risk screener.",
    botTriageAids: "Your inputs suggest running the HIV/AIDS risk screener for a confidential, structured analysis.",
    botTriageVitals: "To check your general health vitals (BMI, Heart rate, Blood pressure), use our local Vitals Tracker.",
    botTriageNone: "I understand. If you have specific physical symptoms like chest pain, joint stiffness, high fever, or chronic cough, describe them so I can guide you. If you feel unwell, please consult a medical professional.",
    startButton: "Start Checker Now",
    
    // Health Checker UI
    hearQuestion: "Hear Question",
    questionProgress: "Question",
    of: "of",
    runningML: "Running ML prediction…",
    analyzingResponses: "Analyzing your responses with the calibrated model",
    mlRisk: "ML Risk Prediction",
    riskLevel: "Risk Level",
    probability: "Probability",
    modelConfidence: "Model Confidence",
    topRiskFactors: "Top Risk Factors",
    downloadReport: "🧾 Download ML Report (PDF)",
    allHospitals: "🏥 All Hospitals",
    govHospitals: "🏛️ Government",
    privateHospitals: "🏥 Private",
    findHospitals: "Find Nearby Hospitals",
    locatingHospitals: "Locating nearby hospitals…",
    largerMap: "Open larger",
    previewMap: "Preview Map",
    directions: "Directions",
    explainability: "Model Explainability",
    backHome: "← Back to Home",
  },
  हिन्दी: {
    // Nav & General
    home: "मुख्य पृष्ठ",
    services: "सेवाएं",
    reports: "रिपोर्ट्स",
    contact: "संपर्क",
    signOut: "साइन आउट",
    logoTitle: "एआई अर्ली",
    logoSubtitle: "डिटेक्टर",
    High: "उच्च",
    Moderate: "मध्यम",
    Low: "कम",
    
    // Hero
    heroTitle: "एआई अर्ली",
    heroGradient: "डिटेक्टर",
    heroSub: "गंभीर स्वास्थ्य समस्याओं के बढ़ने से पहले उनकी जांच के लिए डीप लर्निंग मॉडल के साथ आपको सशक्त बनाना। स्मार्ट देखभाल। शीघ्र जांच।",
    getStarted: "स्क्रीनिंग शुरू करें",
    vitalsCalc: "वाइटल्स मापें",
    
    // Services Section
    whatWeDo: "हम क्या करते हैं",
    ourServices: "हमारी सेवाएं",
    servicesTitle: "विश्वसनीय स्वास्थ्य जानकारी,",
    servicesSubtitle: "एक नज़र में",
    servicesDesc: "एआई-संचालित शीघ्र जांच शुरू करने के लिए एक मॉड्यूल चुनें।",
    openModule: "मॉड्यूल खोलें →",

    // Feature Cards
    triageHubTitle: "लक्षण ट्राइएज हब",
    triageHubDesc: "अपना जोखिम मूल्यांकन शुरू करने के लिए एक विशेष मशीन लर्निंग स्क्रीनिंग मॉड्यूल चुनें।",
    cancerTitle: "कैंसर जांचकर्ता",
    cancerDesc: "उच्च सटीकता के साथ विभिन्न प्रकार के कैंसर के लिए एआई-संचालित प्रारंभिक पहचान और screening।",
    arthritisTitle: "गठिया जांचकर्ता",
    arthritisDesc: "उन्नत एआई मॉडल का उपयोग करके गठिया के लक्षणों का बुद्धिमान विश्लेषण और शीघ्र पता लगाना।",
    heartTitle: "हार्ट अटैक जांचकर्ता",
    heartDesc: "जीवनशैली, महत्वपूर्ण लक्षणों और पारिवारिक इतिहास के कारकों पर एआई का उपयोग करके हृदय जोखिम स्क्रीनिंग।",
    covidTitle: "कोविड-19 जांचकर्ता",
    covidDesc: "वास्तविक समय एआई स्कोरिंग और आत्मविश्वास के साथ लक्षण-आधारित कोविड-19 जोखिम मूल्यांकन।",
    tbTitle: "तपेदिक (टीबी) जांचकर्ता",
    tbDesc: "श्वसन और जोखिम से संबंधित संकेतों का उपयोग करके शीघ्र टीबी जोखिम का पता लगाना।",
    aidsTitle: "एड्स / एचआईवी जांचकर्ता",
    aidsDesc: "मान्य नैदानिक ​​​​जोखिम कारकों के आधार पर गोपनीय एचआईवी/एड्स जोखिम स्क्रीनिंग।",
    reportsTitle: "रिपोर्ट जांचकर्ता",
    reportsDesc: "मशीन लर्निंग द्वारा संचालित स्वचालित मेडिकल रिपोर्ट विश्लेषण और व्याख्या।",
    vitalsTitle: "वाइटल्स ट्रैकर",
    vitalsDesc: "डिवाइस पर ही स्वास्थ्य संकेतकों (बीएमआई, कार्डियो जोन, ब्लड प्रेशर) की गणना और निगरानी करें।",
    adminTitle: "एडमिन",
    adminDesc: "एक केंद्रीकृत डैशबोर्ड से उपयोगकर्ताओं को प्रबंधित करें, विश्लेषण देखें और सिस्टम सेटिंग्स कॉन्फ़िगर करें।",
    assistantTitle: "पर्सनल असिस्टेंट",
    assistantDesc: "दैनिक कदम, पानी का सेवन, नींद के चक्र, कैलोरी ट्रैक करें और दवा अनुस्मारक प्रबंधित करें।",
    mentalTitle: "मानसिक कल्याण केंद्र",
    mentalDesc: "तनाव के स्तर का विश्लेषण करें, निर्देशित श्वास का अभ्यास करें, शांत आवाज़ें सुनें और मूड लॉग करें।",
    doctorTitle: "डॉक्टर और आपातकालीन एसओएस",
    doctorDesc: "तत्काल आपातकालीन एसओएस, नजदीकी क्लीनिक, एम्बुलेंस संपर्क और सीपीआर निर्देश खोजें।",
    diabetesTitle: "मधुमेह और आहार योजनाकार",
    diabetesDesc: "रक्त शर्करा के स्तर की निगरानी करें, स्वस्थ भोजन की योजना बनाएं और कसरत की सिफारिशें देखें।",
    educationTitle: "शैक्षणिक हब",
    educationDesc: "आम स्वास्थ्य मिथकों को दूर करें, इंटरैक्टिव मेडिकल क्विज़ खेलें और स्वास्थ्य समाचार पढ़ें।",
    
    // Adhira Chatbot
    botName: "अधिरा",
    botRole: "एआई स्वास्थ्य सहायक",
    botWelcome: "नमस्ते! मैं अधिरा हूँ, आपकी एआई स्वास्थ्य सहायक। मुझे बताएं कि आप क्या लक्षण महसूस कर रहे हैं (जैसे छाती में दर्द, जोड़ों में अकड़न, खांसी) और मैं आपको सही जांच मॉड्यूल के लिए निर्देशित करूंगी।",
    botPlaceholder: "लक्षण लिखें (जैसे छाती में जकड़न, बुखार)...",
    botSend: "भेजें",
    botTriageHeart: "आपके लक्षण संभावित हृदय संबंधी चिंता का संकेत देते हैं। कृपया तुरंत हमारा हार्ट अटैक जोखिम जांच मॉड्यूल शुरू करें।",
    botTriageArthritis: "आपने जोड़ों के लक्षणों का उल्लेख किया है, जो संभावित गठिया (गठिया रोग) की चिंता का संकेत देते हैं। हम आर्थराइटिस जांच की सलाह देते हैं।",
    botTriageCovid: "आपके लक्षणों के आधार पर, COVID-19 का जोखिम हो सकता है। हम अपने COVID-19 जांच मॉड्यूल से जांच करने की सलाह देते हैं।",
    botTriageTb: "आपके श्वसन संबंधी लक्षण तपेदिक (टीबी) के संभावित जोखिम का संकेत देते हैं। कृपया टीबी जोखिम जांच मॉड्यूल चलाएं।",
    botTriageCancer: "आपने ऐसे चेतावनी संकेतों को नोट किया है जो ऑन्कोलॉजिकल (कैंसर) स्थितियों से संबंधित हो सकते हैं। कृपया कैंसर जोखिम जांच पूरी करें।",
    botTriageAids: "आपके इनपुट एक गोपनीय, संरचित विश्लेषण के लिए एचआईवी/एड्स जोखिम जांच चलाने का सुझाव देते हैं।",
    botTriageVitals: "अपने सामान्य स्वास्थ्य वाइटल्स (बीएमआई, हृदय गति, रक्तचाप) की जांच करने के लिए, हमारे स्थानीय वाइटल्स ट्रैकर का उपयोग करें।",
    botTriageNone: "मैं समझती हूँ। यदि आपको छाती में दर्द, जोड़ों में अकड़न, तेज बुखार, या पुरानी खांसी जैसे विशिष्ट शारीरिक लक्षण हैं, तो उनका वर्णन करें ताकि मैं आपका मार्गदर्शन कर सकूं। यदि आप अस्वस्थ महसूस कर रहे हैं, तो कृपया डॉक्टर से संपर्क करें।",
    startButton: "जांच अभी शुरू करें",
    
    // Health Checker UI
    hearQuestion: "प्रश्न सुनें",
    questionProgress: "प्रश्न",
    of: "का",
    runningML: "एआई भविष्यवाणी चल रही है…",
    analyzingResponses: "कैलिब्रेटेड मॉडल के साथ आपकी प्रतिक्रियाओं का विश्लेषण किया जा रहा है",
    mlRisk: "एआई जोखिम भविष्यवाणी",
    riskLevel: "जोखिम स्तर",
    probability: "संभावना",
    modelConfidence: "मॉडल का आत्मविश्वास",
    topRiskFactors: "मुख्य जोखिम कारक",
    downloadReport: "🧾 रिपोर्ट डाउनलोड करें (PDF)",
    allHospitals: "🏥 सभी अस्पताल",
    govHospitals: "🏛️ सरकारी अस्पताल",
    privateHospitals: "🏥 निजी अस्पताल",
    findHospitals: "आस-पास के अस्पताल खोजें",
    locatingHospitals: "आस-पास के अस्पतालों का पता लगाया जा रहा है…",
    largerMap: "बड़ा नक्शा खोलें",
    previewMap: "नक्शा देखें",
    directions: "दिशा-निर्देश",
    explainability: "मॉडल स्पष्टीकरण",
    backHome: "← मुख्य पृष्ठ पर जाएं",

    // Options
    "Yes": "हाँ",
    "No": "नहीं",
    "Sometimes": "कभी-कभी",
    "Rare": "दुर्लभ",
    "Rarely": "दुर्लभ रूप से",
    "Frequent": "अक्सर",
    "Severe": "गंभीर",
    "Mild": "हल्का",
    "Normal": "सामान्य",
    "Uncontrolled": "अनियंत्रित",
    "Controlled": "नियंत्रित",
    "Borderline": "सीमा रेखा",
    "Type 1/2": "टाइप 1/2",
    "Pre-diabetic": "प्री-डायबिटिक",
    "Regular": "नियमित",
    "Occasional": "कभी-कभार",
    "Quit": "छोड़ दिया",
    "Never": "कभी नहीं",
    "Close": "निकट संबंधी",
    "Distant": "दूर के संबंधी",
    "Daily": "दैनिक",
    "Often": "अक्सर",
    "Active": "सक्रिय",
    "Very high": "बहुत अधिक",
    "60+": "60+",
    "45–60": "45-60",
    "30–45": "30-45",
    "<30": "30 से कम",
    "Possible": "संभावित",
    "Irregular": "अनियमित",
    "None": "कोई नहीं",
    "50–60": "50-60",
    "Below 50": "50 से नीचे",
    "NA": "लागू नहीं",

    // Heart attack questions
    "Chest pain or pressure?": "क्या आपको छाती में दर्द या दबाव महसूस होता है?",
    "Pain radiating to arm/jaw/back?": "क्या दर्द बांह/जबड़े/पीठ तक फैलता है?",
    "Shortness of breath on activity?": "क्या गतिविधि करने पर सांस फूलती है?",
    "High blood pressure?": "क्या आपको उच्च रक्तचाप है?",
    "High cholesterol?": "क्या आपका कोलेस्ट्रॉल बढ़ा हुआ है?",
    "Diabetes?": "क्या आपको मधुमेह है?",
    "Smoking?": "क्या आप धूम्रपान करते हैं?",
    "Family history of heart disease?": "क्या परिवार में हृदय रोग का इतिहास है?",
    "Obesity / high BMI?": "क्या मोटापा / बढ़ा हुआ बीएमआई है?",
    "Sedentary lifestyle?": "क्या आपकी जीवनशैली निष्क्रिय/आसीन है?",
    "Frequent palpitations?": "क्या दिल की धड़कन तेज महसूस होती है?",
    "Cold sweats / nausea?": "क्या ठंडा पसीना या मतली महसूस होती है?",
    "Stress level?": "आपका मानसिक तनाव का स्तर क्या है?",
    "Age group?": "आपका आयु वर्ग क्या है?",
    "Previous heart event/surgery?": "क्या पहले कोई हृदय संबंधी समस्या/सर्जरी हुई है?",

    // Cancer questions
    "Unexplained weight loss?": "क्या आपका वजन बिना किसी कारण के तेजी से घटा है?",
    "Persistent fatigue?": "क्या आपको लगातार थकान महसूस होती है?",
    "Any new lump or swelling?": "क्या शरीर में कोई नई गांठ या सूजन महसूस हो रही है?",
    "Smoking or tobacco use?": "धूम्रपान या तंबाकू का सेवन करते हैं?",
    "Family history of cancer?": "क्या परिवार में कैंसर का कोई इतिहास है?",
    "Unusual bleeding?": "क्या शरीर से कोई असामान्य रक्तस्राव होता है?",
    "Persistent cough >3 weeks?": "क्या 3 सप्ताह से अधिक समय से लगातार खांसी है?",
    "Difficulty swallowing?": "क्या निगलने में कठिनाई होती है?",
    "Bowel habit changes?": "क्या मल त्याग की आदतों में बदलाव आया है?",
    "Skin mole changes?": "क्या त्वचा के तिल में कोई बदलाव आया है?",
    "Regular cancer screening?": "क्या आप नियमित रूप से कैंसर जांच करवाते हैं?",
    "Alcohol consumption?": "शराब का सेवन करते हैं?",
    "Night sweats/fever?": "क्या रात में पसीना आना या बुखार महसूस होता है?",
    "Symptoms >3 months?": "क्या ये लक्षण 3 महीने से अधिक समय से हैं?"
  },
  Español: {
    // Nav & General
    home: "Inicio",
    services: "Servicios",
    reports: "Informes",
    contact: "Contacto",
    signOut: "Cerrar sesión",
    logoTitle: "AI Early",
    logoSubtitle: "Detector",
    High: "Alto",
    Moderate: "Moderado",
    Low: "Bajo",
    
    // Hero
    heroTitle: "AI Early",
    heroGradient: "Detector",
    heroSub: "Empoderándole con modelos de Deep Learning locales en el navegador para detectar condiciones de salud críticas antes de que progresen. Detección Temprana.",
    getStarted: "Iniciar Detección",
    vitalsCalc: "Ver Signos Vitales",
    
    // Services Section
    whatWeDo: "Lo que hacemos",
    ourServices: "Nuestros Servicios",
    servicesTitle: "Inteligencia de salud confiable,",
    servicesSubtitle: "de un vistazo",
    servicesDesc: "Elija un módulo para comenzar con la detección temprana impulsada por IA.",
    openModule: "Abrir módulo →",

    // Feature Cards
    triageHubTitle: "Centro de Triaje de Síntomas",
    triageHubDesc: "Seleccione un módulo de evaluación de aprendizaje automático especializado para comenzar su análisis de riesgo.",
    cancerTitle: "Evaluador de Cáncer",
    cancerDesc: "Detección temprana y cribado de varios tipos de cáncer asistidos por IA con alta precisión.",
    arthritisTitle: "Evaluador de Artritis",
    arthritisDesc: "Análisis inteligente y detección temprana de síntomas de artritis con modelos de IA.",
    heartTitle: "Evaluador de Ataque Cardíaco",
    heartDesc: "Cribado de riesgo cardiovascular mediante IA basado en estilo de vida, constantes y antecedentes.",
    covidTitle: "Evaluador de COVID-19",
    covidDesc: "Evaluación de riesgo de COVID-19 basada en síntomas con puntuación de IA en tiempo real.",
    tbTitle: "Evaluador de Tuberculosis",
    tbDesc: "Detección temprana del riesgo de tuberculosis mediante señales respiratorias y de exposición.",
    aidsTitle: "Evaluador de SIDA / VIH",
    aidsDesc: "Cribado confidencial de riesgo de VIH/SIDA basado en factores de riesgo clínicos validados.",
    reportsTitle: "Analizador de Informes",
    reportsDesc: "Análisis e interpretación automatizados de informes médicos mediante aprendizaje automático.",
    vitalsTitle: "Control de Constantes",
    vitalsDesc: "Calcule y controle indicadores de salud (IMC, zonas de entrenamiento, PAM) en su dispositivo.",
    adminTitle: "Administración",
    adminDesc: "Gestione usuarios, vea estadísticas y configure los ajustes del sistema desde un panel centralizado.",
    assistantTitle: "Asistente Personal",
    assistantDesc: "Realice un seguimiento de los pasos, agua, sueño, calorías y recordatorios de medicamentos.",
    mentalTitle: "Bienestar Mental",
    mentalDesc: "Analice el estrés, practique respiración guiada, escuche sonidos relajantes y registre su estado de ánimo.",
    doctorTitle: "Doctor y SOS de Emergencia",
    doctorDesc: "Activar SOS de emergencia, buscar clínicas cercanas, contactos de ambulancia y guías de RCP.",
    diabetesTitle: "Diabetes y Plan de Dieta",
    diabetesDesc: "Controle la glucosa en sangre, planifique comidas saludables y vea ejercicios recomendados.",
    educationTitle: "Centro Educativo",
    educationDesc: "Desmitifique mitos de salud, participe en cuestionarios médicos y lee noticias de bienestar.",
    
    // Adhira Chatbot
    botName: "Adhira",
    botRole: "Asistente IA de Triaje",
    botWelcome: "¡Hola! Soy Adhira, su asistente de salud IA. Describa qué síntomas está experimentando (p. ej., dolor de pecho, rigidez articular, tos) y le guiaré al módulo de detección adecuado.",
    botPlaceholder: "Escriba los síntomas...",
    botSend: "Enviar",
    botTriageHeart: "Sus síntomas sugieren una posible preocupación cardiovascular. Por favor, realice nuestra evaluación de ataque cardíaco inmediatamente.",
    botTriageArthritis: "Mencionó síntomas en las articulaciones, lo que sugiere una posible artritis. Recomendamos usar el evaluador de Artritis.",
    botTriageCovid: "Según sus síntomas, podría haber riesgo de COVID-19. Aconsejamos verificar con el evaluador de COVID-19.",
    botTriageTb: "Sus síntomas respiratorios indican un riesgo potencial de Tuberculosis. Por favor, ejecute el evaluador de TB.",
    botTriageCancer: "Notó señales de advertencia que podrían relacionarse con condiciones oncológicas. Complete el evaluador de riesgo de Cáncer.",
    botTriageAids: "Sus respuestas sugieren ejecutar el evaluador de VIH/SIDA para un análisis confidencial y estructurado.",
    botTriageVitals: "Para verificar sus signos vitales generales (IMC, ritmo cardíaco, presión arterial), use nuestro Rastreador de Vitales.",
    botTriageNone: "Entiendo. Si tiene síntomas específicos, descríbalos. Si se siente mal, consulte a un médico.",
    startButton: "Iniciar Evaluador Ahora",
    
    // Health Checker UI
    hearQuestion: "Escuchar Pregunta",
    questionProgress: "Pregunta",
    of: "de",
    runningML: "Ejecutando predicción de IA…",
    analyzingResponses: "Analizando sus respuestas con el modelo calibrado",
    mlRisk: "Predicción de Riesgo IA",
    riskLevel: "Nivel de Riesgo",
    probability: "Probabilidad",
    modelConfidence: "Confianza del Modelo",
    topRiskFactors: "Factores de Riesgo Principales",
    downloadReport: "🧾 Descargar Informe PDF",
    allHospitals: "🏥 Todos los Hospitales",
    govHospitals: "🏛️ Público",
    privateHospitals: "🏥 Privado",
    findHospitals: "Buscar Hospitales Cercanos",
    locatingHospitals: "Localizando hospitales cercanos…",
    largerMap: "Ver mapa grande",
    previewMap: "Previsualizar Mapa",
    directions: "Direcciones",
    explainability: "Explicabilidad del Modelo",
    backHome: "← Volver al Inicio",

    // Options
    "Yes": "Sí",
    "No": "No",
    "Sometimes": "A veces",
    "Rare": "Raramente",
    "Rarely": "Raramente",
    "Frequent": "Frecuente",
    "Severe": "Grave",
    "Mild": "Leve",
    "Normal": "Normal",
    "Uncontrolled": "Descontrolado",
    "Controlled": "Controlado",
    "Borderline": "Límite",
    "Type 1/2": "Tipo 1/2",
    "Pre-diabetic": "Prediabético",
    "Regular": "Regular",
    "Occasional": "Ocasional",
    "Quit": "Dejado",
    "Never": "Nunca",
    "Close": "Cercano",
    "Distant": "Distante",
    "Daily": "Diario",
    "Often": "Frecuente",
    "Active": "Activo",
    "Very high": "Muy alto",
    "60+": "60+",
    "45–60": "45–60",
    "30–45": "30–45",
    "<30": "<30",
    "Possible": "Posible",
    "Irregular": "Irregular",
    "None": "Ninguno",
    "50–60": "50–60",
    "Below 50": "Menos de 50",
    "NA": "N/A",

    // Heart attack questions
    "Chest pain or pressure?": "¿Dolor o presión en el pecho?",
    "Pain radiating to arm/jaw/back?": "¿Dolor que irradia al brazo/mandíbula/espalda?",
    "Shortness of breath on activity?": "¿Dificultad para respirar al hacer actividad?",
    "High blood pressure?": "¿Presión arterial alta?",
    "High cholesterol?": "¿Colesterol alto?",
    "Diabetes?": "¿Diabetes?",
    "Smoking?": "¿Fumar?",
    "Family history of heart disease?": "¿Antecedentes familiares de enfermedad cardíaca?",
    "Obesity / high BMI?": "¿Obesidad / IMC alto?",
    "Sedentary lifestyle?": "¿Estilo de vida sedentario?",
    "Frequent palpitations?": "¿Palpitaciones frecuentes?",
    "Cold sweats / nausea?": "¿Sudores fríos / náuseas?",
    "Stress level?": "¿Nivel de estrés?",
    "Age group?": "¿Grupo de edad?",
    "Previous heart event/surgery?": "¿Evento/cirugía cardíaca previa?",

    // Cancer questions
    "Unexplained weight loss?": "¿Pérdida de peso inexplicable?",
    "Persistent fatigue?": "¿Fatiga persistente?",
    "Any new lump or swelling?": "¿Algún bulto o hinchazón nuevo?",
    "Smoking or tobacco use?": "¿Uso de tabaco o fumar?",
    "Family history of cancer?": "¿Antecedentes familiares de cáncer?",
    "Unusual bleeding?": "¿Sangrado inusual?",
    "Persistent cough >3 weeks?": "¿Tos persistente durante más de 3 semanas?",
    "Difficulty swallowing?": "¿Dificultad para tragar?",
    "Bowel habit changes?": "¿Cambios en los hábitos intestinales?",
    "Skin mole changes?": "¿Cambios en lunares de la piel?",
    "Regular cancer screening?": "¿Pruebas periódicas de detección de cáncer?",
    "Alcohol consumption?": "¿Consumo de alcohol?",
    "Night sweats/fever?": "¿Sudores nocturnos/fiebre?",
    "Symptoms >3 months?": "¿Síntomas durante más de 3 meses?"
  },
  Français: {
    // Nav & General
    home: "Accueil",
    services: "Services",
    reports: "Rapports",
    contact: "Contact",
    signOut: "Se déconnecter",
    logoTitle: "AI Early",
    logoSubtitle: "Detector",
    High: "Élevé",
    Moderate: "Modéré",
    Low: "Faible",
    
    // Hero
    heroTitle: "AI Early",
    heroGradient: "Detector",
    heroSub: "Vous autonomiser avec des modèles de Deep Learning locaux pour dépister les conditions de santé critiques avant qu'elles ne progressent. Détection Précoce.",
    getStarted: "Commencer le Dépistage",
    vitalsCalc: "Calculer les Signes Vitaux",
    
    // Services Section
    whatWeDo: "Ce que nous faisons",
    ourServices: "Nos Services",
    servicesTitle: "Intelligence de santé fiable,",
    servicesSubtitle: "en un coup d'œil",
    servicesDesc: "Choisissez un module pour commencer le dépistage précoce alimenté par l'IA.",
    openModule: "Ouvrir le module →",

    // Feature Cards
    triageHubTitle: "Centre de Triage des Symptômes",
    triageHubDesc: "Sélectionnez un module de dépistage spécialisé par apprentissage automatique pour commencer votre évaluation des risques.",
    cancerTitle: "Dépistage du Cancer",
    cancerDesc: "Dépistage précoce du cancer alimenté par l'IA avec une grande précision.",
    arthritisTitle: "Dépistage de l'Arthrite",
    arthritisDesc: "Analyse intelligente et détection précoce des symptômes de l'arthrite grâce à l'IA.",
    heartTitle: "Dépistage Cardiaque",
    heartDesc: "Dépistage des risques cardiovasculaires par l'IA basé sur le mode de vie et les antécédents.",
    covidTitle: "Dépistage COVID-19",
    covidDesc: "Évaluation du risque de COVID-19 basée sur les symptômes avec score IA en temps réel.",
    tbTitle: "Dépistage Tuberculose",
    tbDesc: "Détection précoce du risque de tuberculose à l'aide de signaux respiratoires.",
    aidsTitle: "Dépistage SIDA / VIH",
    aidsDesc: "Dépistage confidentiel du VIH/SIDA basé sur des facteurs cliniques validés.",
    reportsTitle: "Analyse de Rapports",
    reportsDesc: "Analyse et interprétation automatisées des rapports médicaux par apprentissage automatique.",
    vitalsTitle: "Signes Vitaux",
    vitalsDesc: "Calculez et suivez vos indicateurs de santé (IMC, zones cardio, PAM) sur votre appareil.",
    adminTitle: "Administration",
    adminDesc: "Gérez les utilisateurs, consultez les statistiques et configurez le système depuis un tableau de bord.",
    assistantTitle: "Assistant Personnel",
    assistantDesc: "Suivez vos pas quotidiens, eau, cycles de sommeil, calories et rappels de médicaments.",
    mentalTitle: "Bien-être Mental",
    mentalDesc: "Évaluez le stress, pratiquez la respiration guidée, écoutez des sons et notez votre humeur.",
    doctorTitle: "Médecin & SOS Urgence",
    doctorDesc: "Bouton SOS d'urgence, recherche de cliniques, numéros d'ambulance et guides de RCR.",
    diabetesTitle: "Diabète & Diététique",
    diabetesDesc: "Suivez votre glycémie, planifiez des repas personnalisés et consultez les exercices.",
    educationTitle: "Espace Éducatif",
    educationDesc: "Démontez les idées reçues, jouez à des quiz médicaux et lisez des articles santé.",
    
    // Adhira Chatbot
    botName: "Adhira",
    botRole: "Assistant IA de Triage",
    botWelcome: "Bonjour ! Je suis Adhira, votre assistante de santé IA. Décrivez vos symptômes (ex: douleur thoracique, raideur articulaire, toux) et je vous guiderai vers le bon module.",
    botPlaceholder: "Décrivez vos symptômes...",
    botSend: "Envoyer",
    botTriageHeart: "Vos symptômes suggèrent un problème cardiovasculaire potentiel. Veuillez faire notre dépistage de crise cardiaque immédiatement.",
    botTriageArthritis: "Vous avez mentionné des douleurs articulaires, suggérant de l'arthrite. Nous vous conseillons le dépistage de l'Arthrite.",
    botTriageCovid: "Selon vos symptômes, il pourrait y avoir un risque de COVID-19. Nous vous conseillons le dépistage COVID-19.",
    botTriageTb: "Vos symptômes respiratoires indiquent un risque de Tuberculose. Veuillez lancer le dépistage de la tuberculose (TB).",
    botTriageCancer: "Vous avez des signes liés à des conditions oncologiques. Veuillez compléter le dépistage du risque de Cancer.",
    botTriageAids: "Vos réponses suggèrent de lancer le dépistage du VIH/SIDA pour une analyse confidentielle et structurée.",
    botTriageVitals: "Pour vérifier vos signes vitaux généraux (IMC, fréquence cardiaque, tension), utilisez notre calculateur de Signes Vitaux.",
    botTriageNone: "Je comprends. Décrivez vos symptômes afin que je puisse vous guider. En cas de malaise, veuillez consulter un médecin.",
    startButton: "Démarrer le Dépistage",
    
    // Health Checker UI
    hearQuestion: "Écouter la Question",
    questionProgress: "Question",
    of: "sur",
    runningML: "Calcul de la prédiction IA…",
    analyzingResponses: "Analyse de vos réponses avec le modèle calibré",
    mlRisk: "Prédiction de Risque IA",
    riskLevel: "Niveau de Risque",
    probability: "Probabilité",
    modelConfidence: "Confiance du Modèle",
    topRiskFactors: "Facteurs de Risque Principaux",
    downloadReport: "🧾 Télécharger le Rapport PDF",
    allHospitals: "🏥 Tous les Hôpitaux",
    govHospitals: "🏛️ Public",
    privateHospitals: "🏥 Privé",
    findHospitals: "Trouver les Hôpitaux Proches",
    locatingHospitals: "Localisation des hôpitaux…",
    largerMap: "Agrandir la carte",
    previewMap: "Aperçu de la Carte",
    directions: "Itinéraire",
    explainability: "Explicabilité du Modèle",
    backHome: "← Retour à l'Accueil",

    // Options
    "Yes": "Oui",
    "No": "Non",
    "Sometimes": "Parfois",
    "Rare": "Rarement",
    "Rarely": "Rarement",
    "Frequent": "Fréquent",
    "Severe": "Grave",
    "Mild": "Léger",
    "Normal": "Normal",
    "Uncontrolled": "Incontrôlé",
    "Controlled": "Contrôlé",
    "Borderline": "Limite",
    "Type 1/2": "Type 1/2",
    "Pre-diabetic": "Pré-diabétique",
    "Regular": "Régulier",
    "Occasional": "Occasionnel",
    "Quit": "Arrêté",
    "Never": "Jamais",
    "Close": "Proche",
    "Distant": "Éloigné",
    "Daily": "Quotidien",
    "Often": "Souvent",
    "Active": "Actif",
    "Very high": "Très élevé",
    "60+": "60+",
    "45–60": "45-60",
    "30–45": "30-45",
    "<30": "<30",
    "Possible": "Possible",
    "Irregular": "Irrégulier",
    "None": "Aucun",
    "50–60": "50–60",
    "Below 50": "Moins de 50",
    "NA": "N/A",

    // Heart attack questions
    "Chest pain or pressure?": "Douleur ou pression thoracique ?",
    "Pain radiating to arm/jaw/back?": "Douleur irradiant vers le bras/la mâchoire/le dos ?",
    "Shortness of breath on activity?": "Essoufflement à l'effort ?",
    "High blood pressure?": "Hypertension artérielle ?",
    "High cholesterol?": "Hypercholestérolémie ?",
    "Diabetes?": "Diabète ?",
    "Smoking?": "Tabagisme ?",
    "Family history of heart disease?": "Antécédents familiaux de maladie cardiaque ?",
    "Obesity / high BMI?": "Obésité / IMC élevé ?",
    "Sedentary lifestyle?": "Sédentarité ?",
    "Frequent palpitations?": "Palpitations fréquentes ?",
    "Cold sweats / nausea?": "Sueurs froides / nausées ?",
    "Stress level?": "Niveau de stress ?",
    "Age group?": "Tranche d'âge ?",
    "Previous heart event/surgery?": "Antécédents d'accident ou de chirurgie cardiaque ?",

    // Cancer questions
    "Unexplained weight loss?": "Perte de poids inexpliquée ?",
    "Persistent fatigue?": "Fatigue persistante ?",
    "Any new lump or swelling?": "Nouvelle grosseur ou gonflement ?",
    "Smoking or tobacco use?": "Usage du tabac ou de la cigarette ?",
    "Family history of cancer?": "Antécédents familiaux de cancer ?",
    "Unusual bleeding?": "Saignements inhabituels ?",
    "Persistent cough >3 weeks?": "Toux persistante depuis plus de 3 semaines ?",
    "Difficulty swallowing?": "Difficulté à avaler ?",
    "Bowel habit changes?": "Changements du transit intestinal ?",
    "Skin mole changes?": "Modifications d'un grain de beauté ?",
    "Regular cancer screening?": "Dépistage régulier du cancer ?",
    "Alcohol consumption?": "Consommation d'alcool ?",
    "Night sweats/fever?": "Sueurs nocturnes / fièvre ?",
    "Symptoms >3 months?": "Symptômes depuis plus de 3 mois ?"
  },
  Deutsch: {
    // Nav & General
    home: "Startseite",
    services: "Dienste",
    reports: "Berichte",
    contact: "Kontakt",
    signOut: "Abmelden",
    logoTitle: "AI Early",
    logoSubtitle: "Detector",
    High: "Hoch",
    Moderate: "Mittelschwer",
    Low: "Niedrig",
    
    // Hero
    heroTitle: "AI Early",
    heroGradient: "Detector",
    heroSub: "Unterstützung durch lokale Deep-Learning-Modelle zur Früherkennung kritischer Krankheiten vor dem Fortschreiten. Intelligente Vorsorge.",
    getStarted: "Früherkennung Starten",
    vitalsCalc: "Vitalwerte Berechnen",
    
    // Services Section
    whatWeDo: "Was wir tun",
    ourServices: "Unsere Dienste",
    servicesTitle: "Zuverlässige Gesundheitsanalysen,",
    servicesSubtitle: "auf einen Blick",
    servicesDesc: "Wählen Sie ein Modul, um mit der KI-gestützten Früherkennung zu beginnen.",
    openModule: "Modul öffnen →",

    // Feature Cards
    triageHubTitle: "Symptom-Triage-Zentrum",
    triageHubDesc: "Wählen Sie ein spezialisiertes Screening-Modul für maschinelles Lernen, um Ihre Risikobewertung zu starten.",
    cancerTitle: "Krebs-Früherkennung",
    cancerDesc: "KI-gestützte Früherkennung und Screening auf verschiedene Krebsarten mit hoher Genauigkeit.",
    arthritisTitle: "Arthritis-Früherkennung",
    arthritisDesc: "Intelligente Analyse und Früherkennung von Arthritissymptomen mittels fortschrittlicher KI.",
    heartTitle: "Herzinfarkt-Früherkennung",
    heartDesc: "Kardiovaskuläres Risiko-Screening mittels KI auf Basis von Lebensstil und Vitalwerten.",
    covidTitle: "COVID-19-Früherkennung",
    covidDesc: "Symptombasiertes COVID-19-Risiko-Screening mit KI-Scoring in Echtzeit.",
    tbTitle: "Tuberkulose-Früherkennung",
    tbDesc: "Früherkennung des Tuberkuloserisikos anhand von Atemwegs- und Kontaktsignalen.",
    aidsTitle: "AIDS / HIV-Früherkennung",
    aidsDesc: "Vertrauliches HIV/AIDS-Risiko-Screening auf der Grundlage validierter klinischer Faktoren.",
    reportsTitle: "Bericht-Analyser",
    reportsDesc: "Automatisierte medizinische Berichtsanalyse und -interpretation durch maschinelles Lernen.",
    vitalsTitle: "Vitalwerte-Tracker",
    vitalsDesc: "Berechnen und überwachen Sie Gesundheitsindikatoren (BMI, Herzfrequenzbereiche, MAP) auf dem Gerät.",
    adminTitle: "Verwaltung",
    adminDesc: "Verwalten Sie Benutzer, zeigen Sie Statistiken an und konfigurieren Sie das System zentral.",
    assistantTitle: "Persönlicher Assistent",
    assistantDesc: "Verfolgen Sie Schritte, Wasser, Schlaf, Kalorien und verwalten Sie Medikamentenerinnerungen.",
    mentalTitle: "Mentale Gesundheit",
    mentalDesc: "Stress analysieren, geführte Atmung üben, Entspannungsgeräusche hören und Stimmung loggen.",
    doctorTitle: "Arzt & Notfall-SOS",
    doctorDesc: "Sofortiger Notfall-SOS-Auslöser, Suche nach Kliniken, Krankenwagen-Kontakten und Reanimationsanleitungen.",
    diabetesTitle: "Diabetes & Diätplaner",
    diabetesDesc: "Blutzucker überwachen, gesunde Mahlzeiten planen und Trainingsempfehlungen ansehen.",
    educationTitle: "Bildungsportal",
    educationDesc: "Gesundheitsmythen aufdecken, medizinische Quizze spielen und Wellness-News lesen.",
    
    // Adhira Chatbot
    botName: "Adhira",
    botRole: "KI-Triage-Assistentin",
    botWelcome: "Hallo! Ich bin Adhira, Ihre KI-Gesundheitsassistentin. Beschreiben Sie Ihre Symptome (z.B. Brustschmerzen, Gelenksteife, Husten) und ich leite Sie zum richtigen Früherkennungsmodul weiter.",
    botPlaceholder: "Symptome eingeben...",
    botSend: "Senden",
    botTriageHeart: "Ihre Symptome deuten auf ein potenzielles kardiovaskuläres Problem hin. Bitte machen Sie sofort unseren Herzinfarkt-Risiko-Test.",
    botTriageArthritis: "Sie haben Gelenksymptome erwähnt, was auf Arthritis hindeutet. Wir empfehlen unseren Arthritis-Screener.",
    botTriageCovid: "Aufgrund Ihrer Symptome besteht ein COVID-19-Risiko. Wir empfehlen die Überprüfung mit unserem COVID-19-Screener.",
    botTriageTb: "Ihre Atemwegssymptome deuten auf Tuberkulose hin. Bitte führen Sie den TB-Risiko-Screener aus.",
    botTriageCancer: "Sie haben Warnzeichen festgestellt, die auf Krebserkrankungen hindeuten könnten. Bitte machen Sie den Krebsrisiko-Screener.",
    botTriageAids: "Ihre Angaben legen nahe, den HIV/AIDS-Risiko-Screener für eine vertrauliche, strukturierte Analyse durchzuführen.",
    botTriageVitals: "Nutzen Sie unseren lokalen Vitalwerte-Tracker, um Ihre Vitalwerte (BMI, Herzfrequenz, Blutdruck) zu überprüfen.",
    botTriageNone: "Ich verstehe. Beschreiben Sie Ihre Symptome, damit ich Sie anleiten kann. Wenn Sie sich unwohl fühlen, bitte konsultieren Sie einen Arzt.",
    startButton: "Screener Jetzt Starten",
    
    // Health Checker UI
    hearQuestion: "Frage Vorlesen",
    questionProgress: "Frage",
    of: "von",
    runningML: "KI-Vorhersage wird ausgeführt…",
    analyzingResponses: "Analysieren Ihrer Antworten mit dem kalibrierten Modell",
    mlRisk: "KI-Risikovorhersage",
    riskLevel: "Risiko-Stufe",
    probability: "Wahrscheinlichkeit",
    modelConfidence: "Modellsicherheit",
    topRiskFactors: "Hauptrisikofaktoren",
    downloadReport: "🧾 PDF-Bericht Herunterladen",
    allHospitals: "🏥 Alle Krankenhäuser",
    govHospitals: "🏛️ Öffentlich",
    privateHospitals: "🏥 Privat",
    findHospitals: "Krankenhäuser in der Nähe Finden",
    locatingHospitals: "Krankenhäuser werden gesucht…",
    largerMap: "Karte vergrößern",
    previewMap: "Karten-Vorschau",
    directions: "Wegbeschreibung",
    explainability: "Modellerklärbarkeit",
    backHome: "← Zurück zur Startseite",

    // Options
    "Yes": "Ja",
    "No": "Nein",
    "Sometimes": "Manchmal",
    "Rare": "Selten",
    "Rarely": "Selten",
    "Frequent": "Häufig",
    "Severe": "Schwer",
    "Mild": "Mild",
    "Normal": "Normal",
    "Uncontrolled": "Unkontrolliert",
    "Controlled": "Kontrolliert",
    "Borderline": "Grenzwertig",
    "Type 1/2": "Typ 1/2",
    "Pre-diabetic": "Prädiabetisch",
    "Regular": "Regelmäßig",
    "Occasional": "Gelegentlich",
    "Quit": "Aufgegeben",
    "Never": "Nie",
    "Close": "Nah",
    "Distant": "Entfernt",
    "Daily": "Täglich",
    "Often": "Oft",
    "Active": "Aktiv",
    "Very high": "Sehr hoch",
    "60+": "60+",
    "45–60": "45-60",
    "30–45": "30-45",
    "<30": "<30",
    "Possible": "Möglich",
    "Irregular": "Unregelmäßig",
    "None": "Keine",
    "50–60": "50-60",
    "Below 50": "Unter 50",
    "NA": "N/A",

    // Heart attack questions
    "Chest pain or pressure?": "Brustschmerzen oder Druckgefühl?",
    "Pain radiating to arm/jaw/back?": "Schmerzen, die in den Arm/Kiefer/Rücken ausstrahlen?",
    "Shortness of breath on activity?": "Kurzatmigkeit bei Belastung?",
    "High blood pressure?": "Bluthochdruck?",
    "High cholesterol?": "Hohes Cholesterin?",
    "Diabetes?": "Diabetes?",
    "Smoking?": "Rauchen?",
    "Family history of heart disease?": "Kardiovaskuläre Krankheiten in der Familie?",
    "Obesity / high BMI?": "Fettleibigkeit / hoher BMI?",
    "Sedentary lifestyle?": "Bewegungsarmut?",
    "Frequent palpitations?": "Häufiges Herzklopfen?",
    "Cold sweats / nausea?": "Kalter Schweiß / Übelkeit?",
    "Stress level?": "Stresslevel?",
    "Age group?": "Altersgruppe?",
    "Previous heart event/surgery?": "Früheres Herzereignis oder Herz-OP?",

    // Cancer questions
    "Unexplained weight loss?": "Unerklärlicher Gewichtsverlust?",
    "Persistent fatigue?": "Ständige Müdigkeit?",
    "Any new lump or swelling?": "Neue Knoten oder Schwellungen?",
    "Smoking or tobacco use?": "Tabak- oder Zigarettenkonsum?",
    "Family history of cancer?": "Krebserkrankungen in der Familie?",
    "Unusual bleeding?": "Ungewöhnliche Blutungen?",
    "Persistent cough >3 weeks?": "Anhaltender Husten seit über 3 Wochen?",
    "Difficulty swallowing?": "Schluckbeschwerden?",
    "Bowel habit changes?": "Darmgewohnheiten verändert?",
    "Skin mole changes?": "Veränderungen der Muttermale?",
    "Regular cancer screening?": "Regelmäßige Krebsvorsorge?",
    "Alcohol consumption?": "Alkoholkonsum?",
    "Night sweats/fever?": "Nächtliches Schwitzen oder Fieber?",
    "Symptoms >3 months?": "Symptome seit über 3 Monaten?"
  },
  中文: {
    // Nav & General
    home: "首页",
    services: "服务",
    reports: "报告",
    contact: "联系",
    signOut: "退出登录",
    logoTitle: "AI Early",
    logoSubtitle: "检测器",
    High: "高",
    Moderate: "中等",
    Low: "低",
    
    // Hero
    heroTitle: "AI Early",
    heroGradient: "检测器",
    heroSub: "通过浏览器端运行的深度学习模型，在病情恶化之前对关键健康状况进行筛查。智能护理，及早发现。",
    getStarted: "开始筛查",
    vitalsCalc: "测量生命体征",
    
    // Services Section
    whatWeDo: "我们的业务",
    ourServices: "我们的服务",
    servicesTitle: "值得信赖的健康智能,",
    servicesSubtitle: "一目了然",
    servicesDesc: "选择一个模块，开始人工智能驱动的早期检测。",
    openModule: "打开模块 →",

    // Feature Cards
    triageHubTitle: "症状分诊中心",
    triageHubDesc: "选择一个专业的机器学习筛查模块来开始您的患病风险评估。",
    cancerTitle: "癌症筛查器",
    cancerDesc: "利用AI高精度进行各种癌症的早期检测和筛查。",
    arthritisTitle: "关节炎筛查器",
    arthritisDesc: "使用先进的人工智能模型对关节炎症状进行智能分析和早期检测。",
    heartTitle: "心脏病筛查器",
    heartDesc: "结合生活方式、生命体征和家族史，使用AI评估心血管患病风险。",
    covidTitle: "新冠筛查器",
    covidDesc: "基于症状的新冠风险评估，配备实时AI风险评分和可信度。",
    tbTitle: "肺结核筛查器",
    tbDesc: "结合呼吸道和接触史等信号，及早进行肺结核患病风险检测。",
    aidsTitle: "艾滋病筛查器",
    aidsDesc: "基于已验证的临床风险因子，提供机密的艾滋病/HIV风险筛查。",
    reportsTitle: "报告分析器",
    reportsDesc: "基于机器学习，实现医疗报告的自动化分析与解读。",
    vitalsTitle: "体征追踪器",
    vitalsDesc: "在设备上计算并监测各项健康体征（BMI、心率区间、平均动脉压）。",
    adminTitle: "后台管理",
    adminDesc: "在一个中心化的仪表板中管理用户、查看分析并配置系统设置。",
    assistantTitle: "个人健康助手",
    assistantDesc: "记录每日步数、饮水量、睡眠周期、卡路里，并管理用药提醒。",
    mentalTitle: "心理健康中心",
    mentalDesc: "评估压力指数、练习呼吸冥想、播放白噪音，并记录情绪日志。",
    doctorTitle: "医生与紧急求助 (SOS)",
    doctorDesc: "一键发送SOS紧急报警，查找附近诊所、救护车电话及CPR急救演示。",
    diabetesTitle: "糖尿病与饮食计划",
    diabetesDesc: "监测血糖变化、规划健康降糖食谱，并查看运动康复指南。",
    educationTitle: "健康科普宣教",
    educationDesc: "粉碎常见医学谣言、挑战健康常识趣味问答，并阅读养生资讯。",
    
    // Adhira Chatbot
    botName: "Adhira",
    botRole: "人工智能健康分诊助手",
    botWelcome: "您好！我是 Adhira，您的人工智能健康助手。请描述您正在经历的症状（例如胸痛、关节僵硬、咳嗽），我将引导您前往正确的筛查模块。",
    botPlaceholder: "输入您的症状...",
    botSend: "发送",
    botTriageHeart: "您的症状表明可能存在心血管问题。请立即进行我们的心脏病发作风险筛查。",
    botTriageArthritis: "您提到了关节症状，这表明可能存在关节炎。我们建议进行关节炎筛查。",
    botTriageCovid: "根据您的症状，可能会有感染新冠病毒的风险。我们建议使用新冠病毒筛查器进行检查。",
    botTriageTb: "您的呼吸道症状表明可能存在肺结核风险。请运行肺结核风险筛查。",
    botTriageCancer: "您注意到了可能与肿瘤状况相关的警告信号。请完成癌症风险筛查。",
    botTriageAids: "您的输入建议运行艾滋病毒/艾滋病风险筛查，以进行机密、结构化的分析。",
    botTriageVitals: "要检查您的基本健康体征（BMI、心率、血压），请使用我们的本地体征追踪器。",
    botTriageNone: "我明白。如果您有特定症状，请进行描述以方便我指引您。如果您感到明显不适，请及时就医。",
    startButton: "立即开始筛查",
    
    // Health Checker UI
    hearQuestion: "听取问题",
    questionProgress: "问题",
    of: "之",
    runningML: "正在运行人工智能预测…",
    analyzingResponses: "使用校准后的模型分析您的回答",
    mlRisk: "AI 风险预测",
    riskLevel: "风险等级",
    probability: "概率",
    modelConfidence: "模型置信度",
    topRiskFactors: "主要风险因素",
    downloadReport: "🧾 下载 PDF 报告",
    allHospitals: "🏥 所有医院",
    govHospitals: "🏛️ 公立",
    privateHospitals: "🏥 私立",
    findHospitals: "查找附近医院",
    locatingHospitals: "正在定位附近医院…",
    largerMap: "打开大地图",
    previewMap: "预览地图",
    directions: "路线导航",
    explainability: "模型可解释性",
    backHome: "← 返回首页",

    // Options
    "Yes": "是",
    "No": "否",
    "Sometimes": "有时",
    "Rare": "很少",
    "Rarely": "很少",
    "Frequent": "经常",
    "Severe": "严重",
    "Mild": "轻微",
    "Normal": "正常",
    "Uncontrolled": "失控",
    "Controlled": "受控",
    "Borderline": "临界",
    "Type 1/2": "1/2型",
    "Pre-diabetic": "糖尿病前期",
    "Regular": "规律",
    "Occasional": "偶尔",
    "Quit": "已戒",
    "Never": "从不",
    "Close": "直系亲属",
    "Distant": "旁系亲属",
    "Daily": "每天",
    "Often": "经常",
    "Active": "活跃",
    "Very high": "非常高",
    "60+": "60岁以上",
    "45–60": "45-60岁",
    "30–45": "30-45岁",
    "<30": "30岁以下",
    "Possible": "可能",
    "Irregular": "不规律",
    "None": "无",
    "50–60": "50-60岁",
    "Below 50": "50岁以下",
    "NA": "不适用",

    // Heart attack questions
    "Chest pain or pressure?": "是否感到胸痛或压迫感？",
    "Pain radiating to arm/jaw/back?": "疼痛是否放射至手臂/下颌/背部？",
    "Shortness of breath on activity?": "活动时是否感到呼吸急促？",
    "High blood pressure?": "是否患有高血压？",
    "High cholesterol?": "是否患有高胆固醇？",
    "Diabetes?": "是否患有糖尿病？",
    "Smoking?": "是否吸烟？",
    "Family history of heart disease?": "是否有家族心脏病史？",
    "Obesity / high BMI?": "是否肥胖或BMI偏高？",
    "Sedentary lifestyle?": "是否久坐少动？",
    "Frequent palpitations?": "是否经常心慌/心悸？",
    "Cold sweats / nausea?": "是否出冷汗或感到恶心？",
    "Stress level?": "精神压力处于何种水平？",
    "Age group?": "您属于哪个年龄段？",
    "Previous heart event/surgery?": "此前是否有过心脏病发作史或心脏手术？",

    // Cancer questions
    "Unexplained weight loss?": "体重是否无故明显减轻？",
    "Persistent fatigue?": "是否感到持续疲劳？",
    "Any new lump or swelling?": "是否有新出现的肿块或肿胀？",
    "Smoking or tobacco use?": "是否吸烟或使用烟草？",
    "Family history of cancer?": "是否有家族癌症史？",
    "Unusual bleeding?": "是否有异常出血情况？",
    "Persistent cough >3 weeks?": "是否咳嗽持续超过三周？",
    "Difficulty swallowing?": "是否感到吞咽困难？",
    "Bowel habit changes?": "排便习惯是否有改变？",
    "Skin mole changes?": "皮肤上的痣是否有发生变化？",
    "Regular cancer screening?": "是否定期进行癌症筛查？",
    "Alcohol consumption?": "是否饮酒？",
    "Night sweats/fever?": "是否有夜间盗汗或发热情况？",
    "Symptoms >3 months?": "上述症状是否已持续三个月以上？"
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "English",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("pref-lang") as Language) || "English";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("pref-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["English"]?.[key] || key;
  };

  useEffect(() => {
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "pref-lang" && e.newValue) {
        setLanguageState(e.newValue as Language);
      }
    };
    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
